## Numpy Array Operation :


In [3]:
import numpy as np
print(np.__version__)

2.2.4


### Indexing and Slicing :

In [3]:
arr = np.array([1,2,3,4,5,6,9,5,8])

# Basic Indexing:

print("Basic indexing will be :",arr[5]) # This is how we get specific element via indexing in 1D array.later we will see same for 2-D array but method to indexing will be different. 

# Slicing in array/list:

print("Basic slicing :", arr[2:7])
print("Basic slicing :", arr[3:9])

# Slicing with step(i.e with basic gaping as per suggestion):

print("Slicing with step:",arr[1:8:2]) # Here in [1:8:2]  here 1 is starting inx , 8 is exclusive last idx but 2 here is gap step size.
# Ok we did it! remember that slicing with steps in python(numpy array).

# Negative Indexing and slicing:
print("Negative Indexin:",arr[-3])
print("\nNegative Indexin:",arr[-7])
print("\nNegative slicing:",arr[-6:-3]) # indx element of last element will be exclusive.i.e of -3 i.e 9.
print("\nNegative slicing:",arr[-8:-2]) # indx element of last element will be exclusive i.e of -2 i.e 5.







Basic indexing will be : 6
Basic slicing : [3 4 5 6 9]
Basic slicing : [4 5 6 9 5 8]
Slicing with step: [2 4 6 5]
Negative Indexin: 9

Negative Indexin: 3

Negative slicing: [4 5 6]

Negative slicing: [2 3 4 5 6 9]


### Indexing and Slicing  in 2D-array(Matrices):

In [ ]:
arr_2d = np.array([[2,4,7],
                  [4,8,9],
                  [11,4,6]])

print("specific number in 2D array:\n",arr_2d)

# Indexing in 2D array: via [m,n] here m,n boths start with zeroes values. first we depicts rows no that we preceeds to the column numbers.see
# Grab that syntax perecisely.

print("\nspecific number in 2D array:",arr_2d[2,1]) # here 2,1 depicts row and coloumn no trespectively.
print("\nspecific number in 2D array:",arr_2d[2,2]) 
print("\nspecific number in 2D array:",arr_2d[1,2]) 

# Thats how things works.

# Accesssing entire row and entitre column seperately:
# Grab that syntax perecisely.

print("\nEntire row :",arr_2d[2])  # This is Basic syntax about accessing alone row of 2d array.
print("\nEntire row :",arr_2d[1])  

# lets access coloums alone:

print("\nEntire  column:",arr_2d[:,1]) # This is syntax about the the accesing coloumn seprately. i.e arr_2d[:,colm_no].
print("\nEntire  column:",arr_2d[:,0])




specific number in 2D array:
 [[ 2  4  7]
 [ 4  8  9]
 [11  4  6]]

specific number in 2D array: 4

specific number in 2D array: 6

specific number in 2D array: 9

Entire row : [11  4  6]

Entire row : [4 8 9]

Entire  column: [4 8 4]

Entire  column: [ 2  4 11]


### Sorting in Array :


In [ ]:
unsorted_arr = np.array([2,1,3,2,4,6,7,3,5,8,])

# Sorting in array(ascend order):
# See syntax carefully:

print("Sorted array:",np.sort(unsorted_arr)) # This syntax is somehow complex but stick here.

# Sorting in 2D array:

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])

# In both sorting of 2d array row and column wise the synatax is some complex so get comfortable with it asap.


print("Sorted 2D by column:\n" ,np.sort(arr_2d_unsorted,axis = 0)) # Here see that syntax carefully and axis for column wise sorting will be axis = 0.

print("\nSorted 2D by row:\n" ,np.sort(arr_2d_unsorted,axis = 1)) # Here see that  sybtax cxarfully and axis for row wise sorting will be axis  = 1.


# lets see one more examole :2d array sorting.



arr2d_unsorted = np.array([[1,4,3,5],[2,4,6,5],[3,5,1,8]])

print("Sorted 2D by column:\n" ,np.sort(arr2d_unsorted,axis = 0)) # Here see that syntax carefully and axis for column wise sorting will be axis = 0.

print("Sorted 2D by row:\n" ,np.sort(arr2d_unsorted,axis = 1)) # Here see that syntax carefully and axis for row wise sorting will be axis = 1

# we hope you got it just remember sorting means aranging in sacending order.



Sorted array: [1 2 2 3 3 4 5 6 7 8]
Sorted 2D by column:
 [[1 1]
 [2 2]
 [3 3]]

Sorted 2D by row:
 [[1 3]
 [1 2]
 [2 3]]
Sorted 2D by column:
 [[1 4 1 5]
 [2 4 3 5]
 [3 5 6 8]]
Sorted 2D by row:
 [[1 3 4 5]
 [2 4 5 6]
 [1 3 5 8]]


### Array Filteration : And Masking vs Indexing


In [ ]:
# The special feature about numpy in array filteration is it allows to pass statement for condition etc as parameter in methods associated taht nummpy array which (statement condition) is also known as mask and taht process of doing taht is known as masking.Lets see !

 # MASKING: when we passes statement as condition insted of direct range or idx no and it is totally valid due to numpy.

numbers = np.array([1,2,3,4,5,6,7,8])

 # Basic Indexing in array:
 
num1 = numbers[4] # it is indexing coz here  we will acces array elemt based on passed idx valuei.e 4 = 5
print("print array values at idx no 4 :",num1)

even_numbers = numbers[numbers%2 == 0] # Here masking occurs as we passed statement condition insted of proper index numbers ,this is allowwd due to special power of numpy
                                # Here it is not as like passing idx no we are directly getting values of numbers with our statement condition and concept of masking is dieefrent from indexing.

print("print numbers soecified :",even_numbers)

# Have you seen how a libray makes a language so powerful.

# Remember masking and indexing of array are  different, because indexing access value of array though idx no but masking (statement condition) access the elemet of array directly with what condition say see example.

print array values at idx no 4 : 5
print numbers soecified : [2 4 6 8]


In [ ]:
# Lets see other way to do masking vs indexing

Num = np.array([1,3,5,7,6,4])

mask1 = Num>4 # Mask specified. and in mask a complete expression for evaluation stores.
mask2 = Num<6
mask3 = num=5 # this like case of indexing and as it got only one idx value . so we can say indexig is specialcase (= wala) caes of masking.




print("print no with specified indx no:", Num[mask1])  # Masking  values will get values more that 4 from array unlike urthodox indexing                                                                                    
print("print no with specified indx no:", Num[mask2])  # Masking  values will get values less than that of 6 from array unlike urthodox indexing                                                                                    
print("print no with specified indx no:", Num[mask3])  # Masking  values will get value num = 5 but its convert into case of indexing   as num[5]  like.                                                                            

# cleared !




print no with specified indx no: [5 7 6]
print no with specified indx no: [1 3 5 4]
print no with specified indx no: 4


### Indexing In Array:

In [19]:
number = np.array([5,6,9,2,4,7])


# Accessing more than one element via inedxing in array.
  
print("More than one idx accessing:",number[[2,5]]) # This is right format i.e two pairs of brackets will be used .


# also we can do same as!

indices = [3,2,4]
print("more than one idx accessing:",number[indices])


# Wrong format of accessing multiple idx values.
print(number[2,4]) # error coz we use one pair of bracket

More than one idx accessing: [9 7]
more than one idx accessing: [2 9 4]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### WHERE CLAUSE:



In [29]:
# ITS RESEMBELS TO CONCEPT OF MASKING IN ONE CASE WHILE IN ONE CASE NOT:
# ANALOGY TI WHERE CLAUSE OF IF -ELSE:  YES ITS FUNCTIONIN IS JUTS LIKE WORKING OF IF - ELSE STATEMENT OF PYTHON.SEE

number = np.array([1,4,5,6,7,2])

# see syntax of where clause
# syntx_where = np.where(condition,x,y) 

# Now remember in where clause either put both statement x and y both or niether put any. if you put only one ot will throw error.
# and if condition get satisfied it will print x other wise ot will print y. Now if we don't have x and y both in that case if will simply put cases of masking as we have only condition.see

num_where = np.where(number>5) # Have none of x and y statement.

# if you are using where clause without x and why make it print in following way.  

# print(num_where ) returns evaluted array. but print(number[num1_where]) returns 
print(num_where) # it simply returens arrray and gives idea about that we are talking and created about an evaluted array.
print("\nprint where clause functioning without x and y:",number[num_where]) # it returns actual array as per condition.
  # one more example
num0_where = np.where(number<5)
print("\n",num0_where) # it basically shows evaluated array.
print("\nprint where clause without that x and y:",number[num0_where]) # But without x and y this is right way to get actual array.



# If we are using where clause with x and y we will make it print in such following way. Dont put here as print(number[num1_where]) insted put print(num1_where).
# As here in case where both x and y exist , makes it directly returns actual array with print(num1_where) , instead of printing evaluetd array with print(number[num1_where] no dont do it(no need to do masking) just in case when we both x and y are absent . this is major difference in printing under both condition.

num1_where = np.where(number>2,number*2,number)
print("\n",num1_where) # it simply retursn values in existing order , but values x and y stement ke according change kr ke print karega.
print("\nprint where clause functioning with x an y:",num1_where)

num2_where = np.where(number<4,number*3,number+2)
print("\nprint where clause functioning with x and y:",num2_where) # no masking , directly getting actual array

num3_where = np.where(number>5,True,False)
print("\nprint where clause with x and y:",num3_where)
# here we can put where clause as np.where(number=4, True, False) because its is syntax for array indexig. okay

num4_where = np.where(number<3,True,False)
print("\nprint where clause with x and y:",num4_where)

(array([3, 4]),)

print where clause functioning without x and y: [6 7]

 (array([0, 1, 5]),)

print where clause without that x and y: [1 4 2]

 [ 1  8 10 12 14  2]

print where clause functioning with x an y: [ 1  8 10 12 14  2]

print where clause functioning with x and y: [3 6 7 8 9 6]

print where clause with x and y: [False False False  True  True False]

print where clause with x and y: [ True False False False False  True]


### ADDING AND CONCATENATING ARRAY:

In [ ]:
# ADDINFG ELEMENTS OF ARRAYS:

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

added_array = arr1+arr2 # Its basically adds corresponding elemet of array , but remember to execute this opertion make sure shape of array should be same. other wise result will be error.
print("\nAdding element of array:",added_array) 


# CONCATENATION  IN ARRAY : NO NEED TO HAVE ARRAYS OF SAME SHAPE. we may concatenate multiple arrays same time.
  
concatenation = np.concatenate((arr1,arr2))  # pass value within tuples.
print("\nConcatenation of arrays:",concatenation)

arr3 = np.array([10,20,40,60])
con = np.concatenate((arr3,concatenation))  # this is a,so allowed.
print("\nConcatenation of array:",con)


adding element of array: [5 7 9]

Concatenation of arrays: [1 2 3 4 5 6]

Concatenation of array: [10 20 40 60  1  2  3  4  5  6]


### ARRAY COMPATABIILITY :



In [38]:
# Its validetes the shape of array , whereter it is true or not.
# here we use shape property of array:

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr3 = np.array([9,10,11,12,13])

print("Array Compartability with shape property:",arr1.shape == arr2.shape)
print("\nArray Compartability with shape property:",arr1.shape == arr2.shape)
print("\nArray Compartability with shape property:",arr2.shape == arr3.shape)  # Result will be in boolean value.








Array Compartability with shape property: True

Array Compartability with shape property: True

Array Compartability with shape property: False


### Vstack and Hstack METHOD :


In [ ]:
org_arr = np.array([[2,3],[4,9]])


# vstack : Its is use for creating new row.

new_row = np.array([10,20]) # Specify valid row for row addition. and so specify acordingly.

with_new_row = np.vstack((org_arr,new_row))

print("adding new row via vstack:\n",with_new_row)

new1_row = np.array([11,24])

with1_new_row = np.vstack((with_new_row,new1_row))

print("adding new row via vstack:\n",with1_new_row)


# Hstack : Its is use for colimn addition.

new_col = np.array([[2],[6]])

with_new_col = np.hstack((org_arr,new_col)) # always pass valid array/ matrix so that it get done.

print("\nadding column with hstack:\n", with_new_col)
 
#see  as 
new1_col = np.array([[7],[5]])

with_new1_col = np.hstack((with_new_col,new1_col))
print("\ncomplex column addition  with hstack:",with_new1_col)   # this is how hstack works.



adding new row via vstack:
 [[ 2  3]
 [ 4  9]
 [10 20]]
adding new row via vstack:
 [[ 2  3]
 [ 4  9]
 [10 20]
 [11 24]]

adding column with hstack:
 [[2 3 2]
 [4 9 6]]

complex column addition  with hstack: [[2 3 2 7]
 [4 9 6 5]]


### DELETING ARRAY ELEMENT/ SECTION OF ELEMENTS FROM ARRAY(1D) :

In [ ]:
arr = np.array([1,2,3,4,5,6])

# Here for,deleting element from array  we uses delete method. see
# Aur ek baat this delete method return array after removing specified elements or multiple element , it does't return deleted elemet or deleted section. lets see

# Syntax for deleting element or section.
# Remember delete method take 2 or 3 parameter either combo of array and elemt idx no  or array and slice(idx1,idx2)  and in 2D array name , element , axis = 0 or 1.

# deleted = np.delete(array_name,elemnt) ; array, that elemet thar we want to make delete.
# or 
# deleted = np.delete(array_name,slice(idx1,idx2))  ; array , and deleyted sliced part.

delete5 = np.delete(arr,4)  # and one more thing we may delete only that element that is alredy exist if we want to delete  element outside from idx no range it will throw error.
print(delete5) # It returns array after deleting that element from array.
 
delete3 = np.delete(arr,2)
print(delete3)

delete_6 = np.delete(arr,5) # this and
delete6 = np.delete(arr,len(arr)-1)  # this is same

print(delete_6)
print(delete6)
# Got it !


# Now see deleting multiple elements via slicing.

arr_1 = np.array([10, 20, 30, 40, 50, 60])
new_arr_1 = np.delete(arr_1, slice(2, 5))  # Delete elements from index 2 to 4 (30, 40, 50) here elemet of idxno 5 is exclusive.
print(new_arr_1)

new_arr_2 = np.delete(arr_1,slice())

[1 2 3 4 6]
[1 2 4 5 6]
[1 2 3 4 5]
[1 2 3 4 5]
[10 20 60]


### DELETING ARRAY ELEMENT FROM ARRAY(2D i.e MATRIX) : Row and Column wise.

In [82]:
# Row wise deletion:

arr_0 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

new_arr = np.delete(arr_0, 1, axis=0)  # Delete the 2nd row (index 1 of row) row  wise deletion.
print("\nRow wise deletion using axis= 0:\n",new_arr)


# column wise deletion

arr_c = np.array([[1,2,4],[3,6,9],[10,20,60],[11,22,44]])

new_arr_c = np.delete(arr_c,2,axis = 1) # Delete the 3rd column(index 2 of coloum).
print("\nColumn wise deletion using axis = 1:\n",new_arr_c)


Row wise deletion using axis= 0:
 [[1 2 3]
 [7 8 9]]

Column wise deletion using axis = 1:
 [[ 1  2]
 [ 3  6]
 [10 20]
 [11 22]]
