## COMPLETE NUMPY FOR DATA SCIENCE:(VENV)

## Numpy Array and Basics:


In [1]:
import numpy as np    # here from now np is alias for  our numpy , its we will basically represent numpy as np 
print(np.__version__)

2.2.4


### Creating array from list:


In [52]:
arr_2d = np.array([1,2,3],[5,7,0]) # its throws error bcoz we should always pass parameter within [] since here papameter is itself within [], so we forget actual syntaxual []. so pu it wisely.
print("2D_array:",arr_2d)

# learning while doing mistakes: exploratory study.

TypeError: Field elements must be 2- or 3-tuples, got '5'

In [63]:
# best way to depict 2d array:
arr_2d = np.array([[1,2,3,4],[5,9,17,7]])
print("2D_array:",arr_2d)

2D_array: [[ 1  2  3  4]
 [ 5  9 17  7]]


In [ ]:
# Remember always depict 2d array just we depict matriux in maths ,i.e its order must be properly specified.
# for ex array = ([[2,4,6],[4,8,9,0]]) is wrong bcoz no of elemnt in both row is not same .
# so see 2d array as matrix of maths. number of element in each row must be same , no of elemt in each column must be same.

### List vs Numpy array:

In [62]:
py_list = [1,2,3,4,5]
print("normal python list multiplication:", py_list*2) #  Have you seen usual scaler  list multiplication . i.e list got printed that 2 times 

np_arr = np.array([2,3,4]) # Numpy scaler multiplication leads to elemt wise multiplication.
print("\npython array(numpy array) multiplication:",np_arr*2) # Numpy array multiplication by scalers leads to element wise multiplication insted of whole list got printed that scalers no of times as we seen in normal python list scaler multiplication.

# Depending upon goal and output we chosse which type of multiplication we want , usually in domain of data  we do lot of numpy array multiplication to train models etc.
# Remember operation time of  python(numpy) array multiplication is much better than the normal python list multiplication . lets see in next cell.

normal python list multiplication: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

python array(numpy array) multiplication: [4 6 8]


In [53]:


import time  # Here we imported time module to get the opertion time.

start = time.time()
py_list = [i*2 for i in range(1000000)]
print( "List operation time:",time.time()- start)

start = time.time()
np_arr = np.arange(1000000) # predefined another method to specify the array in numpy(python).it bassicaly like normal ranges having start stop step . But just it name for craeting numpy array is   np.arange(stat,step,stop).
print("\nNumpy array operation time :",time.time()- start)  
# see array of numpy is more efficient than the normal list python .

List operation time: 0.1264019012451172

Numpy array operation time : 0.0032639503479003906


### Creating array from scracth:

In [54]:
# SOME BASIC TYPES OF ARRAYS:


# ZEROES ARRAY/MATRIX: np.Zeoes((m,n)), here zeroes is predifined method.

Zeroes_matrix = np.zeros((3,5)) # This is syntax of zeroes matrix where (m,n) gives idea about the order of that zeroes matrix.
print("Zeroes matrix of order 3 by 5 :\n",Zeroes_matrix)


Zeroes matrix of order 3 by 5 :
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [55]:
# Ones matrix: np.ones((m,n)) , here ones is predefined as method.
Unit_matrix = np.ones((4,6)) # This is syntax about ones matrix where (m,n) gives idea about the order of ones matrix.
print("Ones matrix of order 4,6 :\n",Unit_matrix)

Ones matrix of order 4,6 :
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [56]:
# Matrix of constant values: np.full((m,n),x) here full is that constant number and (m,n) is order of that constant(x) matrix.
constant_matrix = np.full((4,6),8) # this syntax of constant matrix where (m,n) is order of matrix and each element of matrix wiill be x i.e 8 here
print("constant matrix of 8 of order 4 by 6:\n",constant_matrix)
# got it



constant matrix of 8 of order 4 by 6:
 [[8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]]


In [57]:
# Random array/matrix: It gives random values in array/matrix by own.

random_matrix = np.random.random((2,4)) # here (3,4) is basically a order of that random matrix of (m,n).
print("Random matrix:\n",random_matrix) # got it

# Remember random values function in python will be always between 0 to 1. See here also

Random matrix:
 [[0.76770344 0.47950448 0.2126788  0.63906008]
 [0.50742249 0.22466081 0.46205331 0.06986596]]


In [58]:
# Sequence array: Its not matrix it is 1D array 
 
 # Remember in python range function boundaryvalue(i.e stop values) are exclusive.

seq_array = np.arange(2,20,2) # here firstly , np.arange() is another way syntax for creating array, and (2,20,2) is start, stop, step.
print("sequence array:\n", seq_array) 

sequence array:
 [ 2  4  6  8 10 12 14 16 18]


### Vector(Array) , Matrix , Tensor :

In [59]:
# Vector: It is nothing but array

vector = np.array([1,2,3,4]) # This is basics same syntax for specifying vectors.
print("vector or array:", vector)



vector or array: [1 2 3 4]


In [60]:
# Matrix : its nothing but 2d array
matrix = np.array([[2,4,5,7],[2,9,7,5],[1,8,0,5]]) # Same basic synatx but again the dimension is 2 i.e row column.
print("matrix;\n",matrix)

matrix;
 [[2 4 5 7]
 [2 9 7 5]
 [1 8 0 5]]


In [61]:
# Tensor : its is most complex  array/matrix will multiple duimensions. 
# See basic example of Tensor.

Tensor1 = np.array([
    [1,3,5],[2,4,6],[11,2,8],  
    [5,6,7],[5,8,6],[5,6,7]
])
print("Tensor function is :\n",Tensor1)



# letsee one more 



Tensor2 = np.array([
    [[2,3,4],[5,6,8],[0,6,8]],  # keep things homogeneous as numbers of elemnts in each rows must be same, and no of elemetns in each individual columns  must be same.
    [[10,4,8],[50,50,60],[20,50,60]]
])

print("Tensor function 2 is :\n",Tensor2 )

# this is so short but actual data are so much complex , complex tensors function is requires heavy computation and designed library and ahrware to computation and iteration.

Tensor function is :
 [[ 1  3  5]
 [ 2  4  6]
 [11  2  8]
 [ 5  6  7]
 [ 5  8  6]
 [ 5  6  7]]
Tensor function 2 is :
 [[[ 2  3  4]
  [ 5  6  8]
  [ 0  6  8]]

 [[10  4  8]
  [50 50 60]
  [20 50 60]]]


### Array Properties : 

In [ ]:
# Here to access each properties of Array we have some predefined properties(properties hai na ki methods aur yaha pe paarameter pass hote to yaha pe () closed bracket use nii honge). Lets see

arr = np.array([[2,4,5,8],[4,6,9,0],[12,60,5,6]])
 
 # Shape property: Its gives idea about order of matrix / array etc

shape = arr.shape # Here put arr.shape  not arr.shape() means no closed brackets because these are property not methods jaha par parameter pass karna pade. 
print("shape:", shape)

# Dimension property: Its gives idea about dimension of matrix/array/tensor.

dimension = arr.ndim # again put arr.ndim not arr.ndim() , means no closed braces because it is property not methods jaha pe parameter pass karna pade.
print("dimension of arr is:",dimension)

# Size property: Its gives idea about total element od array/matrix/Tensor.

size = arr.size # again dont use () here again .
print("Size of arr is :",size)

# Data Type property:
Data = arr.dtype
print("data type of arr is :",Data)
# agar ek elemt bhii float kr diiya array ka then it will throw  float data type coz hash(float)>> hash(int).
# BUT in numpy libraries are optamised just because of having similiar data types , we can sure store diffferent data types values but this is not ideal in numpy. 

shape: (3, 4)
dimension of arr is: 2
Size of arr is : 12
data type of arr is : int64


### Array Reshaping:

In [16]:
arr = np.arange(12)
print("Original array:",arr)

# Now we may unlock various property of array because we uses numpy here. let see each one by one.

# Reshaping: it reshaped specifeid array into desired format of array/matrix.

reshaped = arr.reshape((3,4)) # Now this will convert our arr into matrix of order of 3 by 4.
print("\nReshaped array:\n",reshaped)
# Reshaping occurs in valid condition only; for example if we have 12 element in array we can not respahe that array into a matrix of order (3,5) coz 3*5 != 12 but we can craete matrix of order (3,4),(6,2),(2,6) etc valid reshaping.


# flattened property: It converts the matrix into flat arrray see. Its retursn the copy of original array.
flattened = reshaped.flatten()
print("\nflattened the matrix: ",flattened)  # Remember flatten makes copy of original array.But ravel return the changes in original one.But value wise both are same.

# ravel : it also flatten the matrix into the 1d array but , it make return changes in original array.see

raveled = reshaped.ravel()
print("\nraveled array:",raveled)

# Transpose of matrix(T) : we know  it 

Transpose  = reshaped.T
print("\nTranspose of matrix(reshaped):\n",Transpose)


Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

flattened the matrix:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose of matrix(reshaped):
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
